services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3117:3117"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/limedaichat-app
    restart: always

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data:
