services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    environment:
      - NODE_ENV="production"
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${APP_CONTAINER_PORT}
    restart: always
    command: npm run start
