name: Auto Publish Docs Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: limedaichatserver/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('limedaichatserver/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: limedaichatserver
        run: npm install

      - name: Generate Documentation
        working-directory: limedaichatserver
        run: npm run generate-docs

      - name: Upload YML Documentation
        uses: actions/upload-artifact@v3
        with:
          name: api-doc-yml
          path: limedaichatserver/src/docs/openapi.yml

  deploy-doc:
    name: Deploy API documentation
    runs-on: ubuntu-latest
    needs: generate-docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download YML Documentation
        uses: actions/download-artifact@v3
        with:
          name: api-doc-yml

      - name: List downloaded files (optional, for debugging)
        run: ls -la $GITHUB_WORKSPACE

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: limedai
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./openapi.yml

  api-diff:
    name: Check API diff
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download YML Documentation
        uses: actions/download-artifact@v3
        with:
          name: api-doc-yml

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: limedai
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./openapi.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
